name: workout_example
description: Demonstrates how to use the workout plugin.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  workout:
    # When depending on this package from a real application you should use:
    #   workout: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  wear: ^1.1.0

dependency_overrides:
  wear:
    git:
      url: https://github.com/Rexios80/flutter_wear_plugin.git
      ref: c5ca3ce5faf134602e93c1792f1fb0f8a8919465

dev_dependencies:
  rexios_lints: ^5.0.0
