name: workout
description: Run a workout session on Wear OS and Tizen.
version: 1.0.0
author: Rexios
homepage: https://github.com/Rexios80/flutter_workout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  health_tizen:
    git:
      url: git://github.com/Rexios80/plugins.git
      ref: health
      path: packages/health

flutter:
  plugin:
    platforms:
      android:
        package: com.example.workout
        pluginClass: WorkoutPlugin