name: workout
description: Run a workout session on Wear OS and Tizen. Get data such as heart rate in real time.
version: 0.0.5
homepage: https://github.com/Rexios80/flutter_workout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  enum_to_string: ^2.0.1
  permission_handler: ^7.1.0
  permission_handler_tizen: ^1.0.0
  flutter_foreground_plugin: ^0.8.0
  package_info_plus: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.workout
        pluginClass: WorkoutPlugin
      tizen:
        pluginClass: HealthTizenPlugin
        fileName: health_tizen_plugin.h